spring:
  datasource:
    url: jdbc:mysql://localhost:3333/machDB?createDatabaseIfNotExist=true
    username: root
    password: 351995
    hikari:
      max-lifetime: 1800000 # 30m
  jpa:
    hibernate:
      # ddl-auto: create-drop #! So sánh Entity và các bảng để update. Nhưng không xóa các trường trong bảng
      ddl-auto: update
    database: mysql
    show-sql: true #! show các lệnh sql
  mail:
    host: localhost
    port: 1025
    username: leong
    password: leong
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000    
  output:
    ansi:
      enabled: ALWAYS #! enable set log color
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 #! Security Key cho jwt Service
      expiration: 864000000 # a day #! Hết hạn cho token
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:8686/api/v1/auth/activate-account?token=
  admin:
    firstname: leo 
    lastname: ng
    email: leong.dev.35@gmail.com
    password: Db.co0l1
server:
  port: 8686