spring:
  profiles:
    active: dev  
  servlet:
    multipart:
      max-file-size: 50MB #! đặt giới hạn kích thước tối đa cho một file được tải lên thông qua các yêu cầu HTTP multipart
springdoc:
  default-produces-media-type: application/json #! đặt application/json làm loại phương tiện (media type) mặc định mà các endpoint trong API sẽ trả về. Điều này có nghĩa là, nếu không có chỉ định khác, API của bạn sẽ trả về dữ liệu ở định dạng JSON
server:
  tomcat:
    max-connections: 5000 #! số lượng kết nối tối đa
  servlet:
    context-path: /api/v1/ #! tất cả các URL của API trong ứng dụng sẽ bắt đầu với /api/v1/
